"""initial schema

Revision ID: 0d6f177b0755
Revises: 
Create Date: 2026-09-10 13:01:56.321061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6f177b0755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_snapshots_taken_at'), 'equity_snapshots', ['taken_at'], unique=False)
    op.create_table('kill_switch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('nav_at_event', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=True),
    sa.Column('training_data_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_data_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'VALIDATED', 'LIVE', 'REJECTED', 'RETIRED', name='modelstatus'), nullable=False),
    sa.Column('validation_metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oanda_trade_id', sa.String(length=32), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='tradestatus'), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_instrument'), 'trades', ['instrument'], unique=False)
    op.create_index(op.f('ix_trades_oanda_trade_id'), 'trades', ['oanda_trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_oanda_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('model_versions')
    op.drop_table('kill_switch_events')
    op.drop_index(op.f('ix_equity_snapshots_taken_at'), table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    # ### end Alembic commands ###
