"""add instrument and lookback to model_versions

Revision ID: 55699d0508d4
Revises: 0d6f177b0755
Create Date: 2026-09-15 20:24:25.942603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55699d0508d4'
down_revision: Union[str, None] = '0d6f177b0755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('instrument', sa.String(length=16), nullable=True))
    op.add_column('model_versions', sa.Column('lookback', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_model_versions_instrument'), 'model_versions', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_versions_instrument'), table_name='model_versions')
    op.drop_column('model_versions', 'lookback')
    op.drop_column('model_versions', 'instrument')
    # ### end Alembic commands ###
